"use strict"

const CONDITIONAL = {
  SECURITY: ["AUTHORIZATION", "INPUT_VALIDATION", "ABUSE_RESISTANCE"],
  DATA_MIGRATION: ["MIGRATION", "DATA_INTEGRITY", "ROLLBACK_FORWARD_RECOVERY"],
  PUBLIC_CONTRACT: ["PUBLIC_CONTRACT", "BACKWARD_COMPATIBILITY"],
  DEPENDENCY: ["DEPENDENCY_SUPPLY_CHAIN", "LICENSE", "LOCKFILE"],
  DEPLOYMENT: ["DEPLOYMENT", "OBSERVABILITY", "CONFIGURATION"],
  PERFORMANCE: ["PERFORMANCE", "RESOURCE_BUDGET"],
  GENERATED_ARTIFACT: ["GENERATED_ARTIFACT", "REPRODUCIBILITY"],
  DESTRUCTIVE_ACTION: ["SAFEPOINT", "DATA_LOSS"],
  INPUT_VALIDATION: ["INPUT_VALIDATION", "NEGATIVE_PATHS"],
  TEST_RELIABILITY: ["FLAKINESS", "TEST_ISOLATION"],
  HUMAN_OWNERSHIP: ["CODEOWNERS", "HUMAN_APPROVAL"],
  USER_FLOW: ["USER_FLOW", "ERROR_STATES"],
  VISUAL_BEHAVIOR: ["ACCESSIBILITY", "RESPONSIVE_VISUALS"],
  EXTERNAL_TOOLING: ["TOOL_CAPABILITY", "SIDE_EFFECT_BOUNDARY"],
  RECOVERY: ["RECOVERY", "RESILIENCE", "FAILURE_ISOLATION"],
  EXPERIMENTATION: ["EXPERIMENT_ISOLATION", "REVERSIBILITY"],
}

function deriveReviewLenses(riskProfile = {}) {
  const conditional = new Set()
  for (const [dimension, lenses] of Object.entries(CONDITIONAL)) {
    if (["LOW", "HIGH"].includes(String(riskProfile[dimension] || "NONE").toUpperCase())) {
      for (const lens of lenses) conditional.add(lens)
    }
  }
  return {
    schema: "REVIEW_LENS_MATRIX_V1",
    implementation: ["CORRECTNESS", "REGRESSION", "TEST_QUALITY", "MAINTAINABILITY"],
    architecture: ["ARCHITECTURE", "SECURITY_BOUNDARIES", "DATA_SAFETY", "RECOVERY"],
    conditional: [...conditional].sort(),
  }
}

module.exports = { CONDITIONAL, deriveReviewLenses }
